Right now
SimonDamberg/app-theweathermen pull request #56
Opened 2023-12-05 18:04 UTC by tomasote

Closes #46
Closes #45
Closes #44
Closes #43
Closes #42

2023-12-06 12:27 UTC, SimonDamberg requested changes
Looks good, nice work! Remove the unused Lightmode component and change back the URL for the API, then we can merge 👍🏼

2023-12-06 12:27 UTC, SimonDamberg commented on front/app/components/ProfileMenu/LightModeSelectorComponent.tsx
> +}
This component is not used, right?

2023-12-06 12:27 UTC, SimonDamberg commented on front/utils/requestWrapper.ts
> +    return "http://localhost:8000";
This should be reverted since deployed backend now works

2023-12-10 19:07 UTC, tomasote commented
Requested changes fixed

2023-12-10 19:07 UTC, merged