Add new location
SimonDamberg/app-theweathermen pull request #58
Opened 2023-12-07 11:18 UTC by SimonDamberg

Support to add a new location to a user (only works in Sweden due to SMHI api limitations)

Closes #28

2023-12-07 12:38 UTC, theo8theo8 requested changes
Overall looks great, just some minor fixes to be made

2023-12-07 12:38 UTC, theo8theo8 commented on front/app/components/AddLocationDialog.tsx
> +
```suggestion
```
This is not used, right?

2023-12-07 12:38 UTC, theo8theo8 commented on front/public/locales/en/translation.json
> +  "locationAdded": "Location added!"
```suggestion
  "locationAdded": "Location added!",
```

2023-12-07 12:38 UTC, theo8theo8 commented on front/public/locales/sv/translation.json
> +  "locationAdded": "Plats tillagd!"
```suggestion
  "locationAdded": "Plats tillagd!",
```

2023-12-07 12:38 UTC, theo8theo8 commented on front/app/components/LocationCard/LocationCard.tsx
> +                    editing ? "text-green-500" : `text-${theme}-100`
Maybe we should remove the theme green from the selection, since it interferes both with this and the new average-provider?

2023-12-09 19:02 UTC, SimonDamberg commented on front/app/components/LocationCard/LocationCard.tsx
> +                    editing ? "text-green-500" : `text-${theme}-100`
Agree!

2023-12-09 19:05 UTC, merged